version: '3.8'

services:
  # 1. The Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Docker/frontend.dev.dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/Frontend/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0

  # 2. The Backend Service
  backend:
    build:
      context: .
      dockerfile: Docker/backend.dev.dockerfile
    ports:
      - "${REACT_APP_SERVER_PORT}:${REACT_APP_SERVER_PORT}"
      - "${REACT_APP_SOCKET_SERVER_PORT}:${REACT_APP_SOCKET_SERVER_PORT}"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - NODE_ENV=development
      - REACT_APP_DATABASE_HOST=host.docker.internal
    volumes:
      - .:/app
      - /app/node_modules
      - /app/Backend/node_modules
    depends_on:
      - redis

  # 3. The Redis Service
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  db_data: