version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - VITE_USER_API_URL=${VITE_USER_API_URL}
        - VITE_UTILS_API_URL=${VITE_UTILS_API_URL}
        - VITE_PROBLEM_SETS_API_URL=${VITE_PROBLEM_SETS_API_URL}
        - VITE_ROOM_MANAGEMENT_API_URL=${VITE_ROOM_MANAGEMENT_API_URL}
        - REACT_APP_SOCKET_SERVER_PORT=${REACT_APP_SOCKET_SERVER_PORT}
        - REACT_APP_SERVER_PORT=${REACT_APP_SERVER_PORT}
        - REACT_APP_SOCKET_SERVER_URL=${REACT_APP_SOCKET_SERVER_URL}
        - REACT_APP_URL=${REACT_APP_URL}
    ports:
      - "${REACT_APP_SERVER_PORT}:${REACT_APP_SERVER_PORT}"
      - "${REACT_APP_SOCKET_SERVER_PORT}:${REACT_APP_SOCKET_SERVER_PORT}"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - NODE_ENV=production
      - REACT_APP_DATABASE_HOST=host.docker.internal
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  db_data: